name: Conditional examples

on: 
  workflow_dispatch:
    inputs: 
      fail-my-step:
        description: 'Shall we fail the step (yes/no)'
        required: true
        type: string
        default: yes

jobs: 
  the-best-job:
    runs-on: ubuntu-latest
    steps:
      - name: yes was passed in as 'fail-my-step'
        if: inputs.fail-my-step == 'yes'
        run: echo "you said yes :) !"

      - name: no was passed in as 'fail-my-step'
        if: inputs.fail-my-step == 'no'
        run: echo "you said no :( !"
