name : Conditional env and matrix

on: 
  workflow_dispatch:
    inputs:
      viktig:
        description: 'Insert number here (fail if under 7)'
        required: true
        type: number

jobs: 
  the-number-job:
    runs-on: ubuntu-latest
    env:
      NUMBER_INPUT: ${{ inputs.viktig }}
    steps:
      - name: The number was 7 or higher
        if: inputs.viktig >= 7
        run: echo "The number was 7 or higher!"

      - name: The number was lower than 7
        run: |
         echo "The number was lower than 7. The rest of this job will not run."
         echo "Value of inputs.viktig: ${{ inputs.viktig }}"
         if [ $NUMBER_INPUT -lt 7 ]; then
         echo "Exiting with code 42"
         exit 42
         fi
        
      - name: Another step
        run: echo "step that will not run if number is lower than 7..."
          
      - name: Another step
        run: echo "another step that will not run if number is lower than 7..."

  the-env-job:
    runs-on: ubuntu-latest
    env: 
      JOB_ENV: 'Hello from job'

    steps: 
      - name: Testing env var that should be 'Hello from job'
        run: echo "The env var is in fact $JOB_ENV"




      
        
