name : Conditional env and matrix

on: 
  workflow_dispatch:
    inputs:
      viktig:
        description: 'Insert number here (fail if under 7)'
        required: true
        type: number

jobs: 
  the-best-job:
    runs-on: ubuntu-latest
    steps:
      - name: The number was 7 or higher
        if: inputs.viktig >= 7
        run: echo "The number was 7 or higher!"

      - name: The number was lower than 7
        run: |
         echo "The number was lower than 7. The rest of this job will not run."
         echo "Value of inputs.viktig: ${{ inputs.viktig }}"
         if [ ${{ inputs.viktig }} -lt 7 ]; then
         echo "Exiting with code 42"
         exit 42
         fi
        
      - name: Another step
        run: echo "step that will not run if number is lower than 7..."
          
      - name: Another step
        run: echo "another step that will not run if number is lower than 7..."

        
