name: My first workflow

on: workflow_dispatch
#on: [push]

jobs: 
  my-amazing-job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The amazing job has started"
      - run: echo "This was triggered by a ${{ github.event_name }} event."
      - run: echo "This was run on ${{ runner.os }} OS"
      - run: echo "Branch ${{ github.ref }}"
      - run: echo "Repository ${{ github.repository }}"
      - run: echo "The amazing job is complete"
  my-amazing-checkout-job: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cloning${{ github.repository }} to the runner..."
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      - run: echo "Checkout is done"
      - name: List files in repo
        run: | 
          ls -lah ${{ github.workspace }};
          echo "Contents of Instructions.md";
          cat TodoList/Instructions.md;
      - run: echo "This job's status is ${{ job.status }}"
  my-not-as-amazing-job:
    runs-on: ubuntu-latest
    env: 
      lines_of_code: $(find . -name '*.cs' -print0 | xargs -0 cat | wc -l)
    steps: 
      - run: echo "The not so amazing job has started"
      - name: Count Lines of Code (cloc)
  # You may pin to the exact commit or the version.
  # uses: djdefi/cloc-action@6b0244f60427a34a43794f3723267f8add465b04
        uses: djdefi/cloc-action@5
          
      
      - run: echo "The amazing job is complete"
          
        
      

