name: My first workflow

on: workflow_dispatch

jobs: 
  my-amazing-job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The amazing job has started"
      - run: echo "This was triggered by a ${{ github.event_name }} event."
      - run: echo "This was run on ${{ runner.os }} OS"
      - run: echo "Branch ${{ github.ref }}"
      - run: echo "Repository ${{ github.repository }}"
      - run: echo "The amazing job is complete"
      
