name: Practicing workflows

on: workflow_dispatch

jobs: 
  Print-project-name:
    runs-on: ubuntu-latest

    steps:
    - name: Project-name
      run: echo "${{ github.repository }} "

  Print-current-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Branch-name
      run: echo "${{ github.ref }}"
  
